import Head from "next/head";
import { Inter } from "next/font/google";
import { Layout } from "@/layout";

const inter = Inter({ subsets: ["latin"] });
import { Banner, ContactUsHeader, EnquiryForm } from "@/components/pages";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <Layout>
        <div className="row">
          <div className="col-12">
            <ContactUsHeader />
            <div className="container">
              <div className="row justify-content-center">
                <div className="col-md-6">
                  <EnquiryForm />
                </div>
              </div>
            </div>
          </div>
        </div>
        </Layout>
      </main>
    </>
  );
}
