export const CANDIDATE_CREATE_UPDATE_ACTIONS = {
  CANDIDATE_CREATE_UPDATE_ACTIONS_REQUEST:
    "CANDIDATE_CREATE_UPDATE_ACTIONS_REQUEST",
  CANDIDATE_CREATE_UPDATE_ACTIONS_RESPONSE:
    "CANDIDATE_CREATE_UPDATE_ACTIONS_RESPONSE",
  CANDIDATE_CREATE_UPDATE_ACTIONS_ERROR:
    "CANDIDATE_CREATE_UPDATE_ACTIONS_ERROR",
};
