export const SYLLABUS_CREATE_UPDATE_ACTIONS = {
  SYLLABUS_CREATE_UPDATE_ACTIONS_REQUEST:
    'SYLLABUS_CREATE_UPDATE_ACTIONS_REQUEST',
  SYLLABUS_CREATE_UPDATE_ACTIONS_RESPONSE:
    'SYLLABUS_CREATE_UPDATE_ACTIONS_RESPONSE',
  SYLLABUS_CREATE_UPDATE_ACTIONS_ERROR: 'SYLLABUS_CREATE_UPDATE_ACTIONS_ERROR'
};

export const SYLLABUS_LIST_ACTIONS = {
  SYLLABUS_LIST_ACTIONS_REQUEST: 'SYLLABUS_LIST_ACTIONS_REQUEST',
  SYLLABUS_LIST_ACTIONS_RESPONSE: 'SYLLABUS_LIST_ACTIONS_RESPONSE',
  SYLLABUS_LIST_ACTIONS_ERROR: 'SYLLABUS_LIST_ACTIONS_ERROR'
};

export const SYLLABUS_DELETE_ACTIONS = {
  SYLLABUS_DELETE_ACTIONS_REQUEST: 'SYLLABUS_DELETE_ACTIONS_REQUEST',
  SYLLABUS_DELETE_ACTIONS_RESPONSE: 'SYLLABUS_DELETE_ACTIONS_RESPONSE',
  SYLLABUS_DELETE_ACTIONS_ERROR: 'SYLLABUS_DELETE_ACTIONS_ERROR'
};
