import Head from 'next/head'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { QuizeTestCard,QuizeComplite ,GetStartQuize} from '@/components/pages'
export default function Quiztest() {


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={` ${inter.className}`}>


                <div className='row'>
                    <div className='col-12'>
                        <GetStartQuize/>
                        {/* <QuizeTestCard /> */}
                        {/* <QuizeComplite/> */}
                    </div>
                </div>


            </main>
        </>
    )
}
