import Head from "next/head";
//import { Inter } from "next/font/google";
//const inter = Inter({ subsets: ["latin"] });
import {
  QuizeTestCard,
  QuizeComplite,
  GetStartQuize,
} from "@/components/pages";
import { useState } from "react";
import { Layout } from "@/layout";
export default function Quiztest() {
  const [quizeStatus, setQuizeStatus] = useState(0);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main>
        <Layout>
          <div className="row">
            <div className="col-12">
              {quizeStatus === 0 ? (
                <GetStartQuize onQuizeStatusChange={setQuizeStatus} />
              ) : quizeStatus === 1 ? (
                <QuizeTestCard onQuizeStatusChange={setQuizeStatus} />
              ) : (
                quizeStatus === 2 && <QuizeComplite />
              )}

              {/* <QuizeTestCard /> */}
              {/* <QuizeComplite/> */}
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
