export {Banner,AboutCompany,OurCoursesCard,HaveQue,OurCustomer,WhatOfferYou} from './home'
export {OurPromis} from './aboutUs'
export {ContactUsForm} from './contactUs'
export {CourseDetailBanner,CourseCard,CourseDetailContent} from './courses'
export {QuizeTestCard,QuizeComplite,GetStartQuize} from './quiztest'