
export const WEBINARS_LIST_ACTIONS = {
    WEBINARS_LIST_ACTIONS_REQUEST: 'WEBINARS_LIST_ACTIONS_REQUEST',
    WEBINARS_LIST_ACTIONS_RESPONSE: 'WEBINARS_LIST_ACTIONS_RESPONSE',
    WEBINARS_LIST_ACTIONS_ERROR: 'WEBINARS_LIST_ACTIONS_ERROR'
  };

  
export const WEBINARS_DETAIL_ACTIONS = {
  WEBINARS_DETAIL_ACTIONS_REQUEST: 'WEBINARS_DETAIL_ACTIONS_REQUEST',
  WEBINARS_DETAIL_ACTIONS_RESPONSE: 'WEBINARS_DETAIL_ACTIONS_RESPONSE',
  WEBINARS_DETAIL_ACTIONS_ERROR: 'WEBINARS_DETAIL_ACTIONS_ERROR'
};


  
export const WEBINARS_ENROLLED_ACTIONS = {
  WEBINARS_ENROLLED_ACTIONS_REQUEST: 'WEBINARS_ENROLLED_ACTIONS_REQUEST',
  WEBINARS_ENROLLED_ACTIONS_RESPONSE: 'WEBINARS_ENROLLED_ACTIONS_RESPONSE',
  WEBINARS_ENROLLED_ACTIONS_ERROR: 'WEBINARS_ENROLLED_ACTIONS_ERROR'
};
  

export const WEBINARS_ENROLLED_OTP_VERIFY_ACTIONS = {
  WEBINARS_ENROLLED_OTP_VERIFY_ACTIONS_REQUEST: 'WEBINARS_ENROLLED_OTP_VERIFY_ACTIONS_REQUEST',
  WEBINARS_ENROLLED_OTP_VERIFY_ACTIONS_RESPONSE: 'WEBINARS_ENROLLED_OTP_VERIFY_ACTIONS_RESPONSE',
  WEBINARS_ENROLLED_OTP_VERIFY_ACTIONS_ERROR: 'WEBINARS_ENROLLED_OTP_VERIFY_ACTIONS_ERROR'
};

export const WEBINARS_ENROLLED_RESEND_OTP_ACTIONS = {
  WEBINARS_ENROLLED_RESEND_OTP_ACTIONS_REQUEST: 'WEBINARS_ENROLLED_RESEND_OTP_ACTIONS_REQUEST',
  WEBINARS_ENROLLED_RESEND_OTP_ACTIONS_RESPONSE: 'WEBINARS_ENROLLED_RESEND_OTP_ACTIONS_RESPONSE',
  WEBINARS_ENROLLED_RESEND_OTP_ACTIONS_ERROR: 'WEBINARS_ENROLLED_RESEND_OTP_ACTIONS_ERROR'
};
  