
export const WEBINARS_LIST_ACTIONS = {
    WEBINARS_LIST_ACTIONS_REQUEST: 'WEBINARS_LIST_ACTIONS_REQUEST',
    WEBINARS_LIST_ACTIONS_RESPONSE: 'WEBINARS_LIST_ACTIONS_RESPONSE',
    WEBINARS_LIST_ACTIONS_ERROR: 'WEBINARS_LIST_ACTIONS_ERROR'
  };
  