export const SUBSCRIBE_CREATE_ACTIONS = {
  SUBSCRIBE_CREATE_ACTIONS_REQUEST: "SUBSCRIBE_CREATE_ACTIONS_REQUEST",
  SUBSCRIBE_CREATE_ACTIONS_RESPONSE: "SUBSCRIBE_CREATE_ACTIONS_RESPONSE",
  SUBSCRIBE_CREATE_ACTIONS_ERROR: "SUBSCRIBE_CREATE_ACTIONS_ERROR",
};
