import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { NormalButton } from "@/components/pages";
import { Layout } from "@/layout";
const inter = Inter({ subsets: ["latin"] });
import {
  Banner,
  AboutCompany,
  OurCoursesCard,
  HaveQue,
  OurCustomer,
  WhatOfferYou,
} from "@/components/pages";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <main className={`${inter.className}`}>
        <Layout>
          <div className="row">
            <div className="col-12">
              <Banner
                title={
                  <span>
                    Expand your career opportunities with{" "}
                    <span className="text-primary">Acquiring</span>
                  </span>
                }
                description="Acquire Skills for your present (and future). Get started with us"
                bannerImage="/img/banner-img.png"
              />
              <AboutCompany />
              <WhatOfferYou />
              <OurCoursesCard isSwiper={false} />

              <HaveQue />
              {/* <OurCustomer /> */}
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
