import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { NormalButton } from "@/components/pages";
const inter = Inter({ subsets: ["latin"] });
import {
  Banner,
  Description,
  OurCoursesCard,
  HaveQue,
  LiveClassesCard,
  CourseDetailBanner,
} from "@/components/pages";
export default function LiveClassDetail() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <div className="row">
          <div className="col-12">
            <CourseDetailBanner />
            <Description title={"Description"} />
            <LiveClassesCard />
            {/* <WhatOfferYou/>
            <OurCoursesCard isSwiper={false} />
           
            <HaveQue />
            <OurCustomer/> */}
          </div>
        </div>
      </main>
    </>
  );
}
