export {default as Banner} from './banner'
export {default as AboutCompany} from './aboutCompany'
export {default as OurCoursesCard} from './ourCoursesCard'
export {default as HaveQue} from './haveQue'
export {default as OurCustomer} from './ourCustomer'
export {default as WhatOfferYou} from './whatOfferYou'
export {default as UpcommingWebinarsCards} from './upCommingwebinarCards'
export {default as Faq} from './faq'
export {default as StudentFeedBack} from './studentFeedBack'
export {StudentVideoReview} from './studentVideReview'