export const COURSE_ENQUIRY_CREATE_ACTIONS = {
    COURSE_ENQUIRY_CREATE_ACTIONS_REQUEST: 'COURSE_ENQUIRY_CREATE_ACTIONS_REQUEST',
    COURSE_ENQUIRY_CREATE_ACTIONS_RESPONSE: 'COURSE_ENQUIRY_CREATE_ACTIONS_RESPONSE',
    COURSE_ENQUIRY_CREATE_ACTIONS_ERROR: 'COURSE_ENQUIRY_CREATE_ACTIONS_ERROR'
  };

  export const COURSE_ENQUIRY_OTP_VERIFY_ACTIONS = {
    COURSE_ENQUIRY_OTP_VERIFY_ACTIONS_REQUEST: 'COURSE_ENQUIRY_OTP_VERIFY_ACTIONS_REQUEST',
    COURSE_ENQUIRY_OTP_VERIFY_ACTIONS_RESPONSE: 'COURSE_ENQUIRY_OTP_VERIFY_ACTIONS_RESPONSE',
    COURSE_ENQUIRY_OTP_VERIFY_ACTIONS_ERROR: 'COURSE_ENQUIRY_OTP_VERIFY_ACTIONS_ERROR'
  };

  export const COURSE_ENQUIRY_OTP_RESEND_ACTIONS = {
    COURSE_ENQUIRY_OTP_RESEND_ACTIONS_REQUEST: 'COURSE_ENQUIRY_OTP_RESEND_ACTIONS_REQUEST',
    COURSE_ENQUIRY_OTP_RESEND_ACTIONS_RESPONSE: 'COURSE_ENQUIRY_OTP_RESEND_ACTIONS_RESPONSE',
    COURSE_ENQUIRY_OTP_RESEND_ACTIONS_ERROR: 'COURSE_ENQUIRY_OTP_RESEND_ACTIONS_ERROR'
  };