export const COURSE_LIST_ACTIONS = {
  COURSE_LIST_ACTIONS_REQUEST: 'COURSE_LIST_ACTIONS_REQUEST',
  COURSE_LIST_ACTIONS_RESPONSE: 'COURSE_LIST_ACTIONS_RESPONSE',
  COURSE_LIST_ACTIONS_ERROR: 'COURSE_LIST_ACTIONS_ERROR'
};

export const COURSE_CREATE_UPDATE_ACTIONS = {
  COURSE_CREATE_UPDATE_ACTIONS_REQUEST: 'COURSE_CREATE_UPDATE_ACTIONS_REQUEST',
  COURSE_CREATE_UPDATE_ACTIONS_RESPONSE:
    'COURSE_CREATE_UPDATE_ACTIONS_RESPONSE',
  COURSE_CREATE_UPDATE_ACTIONS_ERROR: 'COURSE_CREATE_UPDATE_ACTIONS_ERROR'
};

export const COURSE_DELETE_ACTIONS = {
  COURSE_DELETE_ACTIONS_REQUEST: 'COURSE_DELETE_ACTIONS_REQUEST',
  COURSE_DELETE_ACTIONS_RESPONSE: 'COURSE_DELETE_ACTIONS_RESPONSE',
  COURSE_DELETE_ACTIONS_ERROR: 'COURSE_DELETE_ACTIONS_ERROR'
};
