export const AUTHENTICATE_LOGIN_ACTIONS = {
  AUTHENTICATE_LOGIN_REQUEST: 'AUTHENTICATE_LOGIN_REQUEST',
  AUTHENTICATE_LOGIN_RESPONSE: 'AUTHENTICATE_LOGIN_RESPONSE',
  AUTHENTICATE_LOGIN_ERROR: 'AUTHENTICATE_LOGIN_ERROR'
};


export const AUTHENTICATE_REGISTER_ACTIONS = {
  AUTHENTICATE_REGISTER_REQUEST: 'AUTHENTICATE_REGISTER_REQUEST',
  AUTHENTICATE_REGISTER_RESPONSE: 'AUTHENTICATE_REGISTER_RESPONSE',
  AUTHENTICATE_REGISTER_ERROR: 'AUTHENTICATE_REGISTER_ERROR'
};


export const AUTHENTICATE_REGISTER_EMAIL_VERIFICATION_ACTIONS = {
  AUTHENTICATE_REGISTER_EMAIL_VERIFICATION_REQUEST: 'AUTHENTICATE_REGISTER_EMAIL_VERIFICATION_REQUEST',
  AUTHENTICATE_REGISTER_EMAIL_VERIFICATION_RESPONSE: 'AUTHENTICATE_REGISTER_EMAIL_VERIFICATION_RESPONSE',
  AUTHENTICATE_REGISTER_EMAIL_VERIFICATION_ERROR: 'AUTHENTICATE_REGISTER_EMAIL_VERIFICATION_ERROR'
};


export const AUTHENTICATE_CHANGE_PASSWORD_ACTIONS = {
  AUTHENTICATE_CHANGE_PASSWORD_REQUEST: 'AUTHENTICATE_CHANGE_PASSWORD_REQUEST',
  AUTHENTICATE_CHANGE_PASSWORD_RESPONSE: 'AUTHENTICATE_CHANGE_PASSWORD_RESPONSE',
  AUTHENTICATE_CHANGE_PASSWORD_ERROR: 'AUTHENTICATE_CHANGE_PASSWORD_ERROR'
};

