export const AUTHENTICATE_LOGIN_ACTIONS = {
  AUTHENTICATE_LOGIN_REQUEST: 'AUTHENTICATE_LOGIN_REQUEST',
  AUTHENTICATE_LOGIN_RESPONSE: 'AUTHENTICATE_LOGIN_RESPONSE',
  AUTHENTICATE_LOGIN_ERROR: 'AUTHENTICATE_LOGIN_ERROR'
};
