import Head from "next/head";
import { Inter } from "next/font/google";
import {
  CourseDetailBanner,
  CourseDetailContent,
  CourseVideoCard,
} from "@/components/pages";
import { useEffect } from "react";
import { EXIST_LOCAL_STORAGE } from "@/services/constants";
import { getStorage } from "@/services/helperFunctions";

const inter = Inter({ subsets: ["latin"] });
export default function CourseDetail() {
  useEffect(() => {}, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`vh-100 ${inter.className}`}>
      <div className="container">
        <div className="row">
          <div className="col-8">
            <CourseVideoCard />
          </div>
          <div className="col-4">
            <CourseDetailContent />
          </div>
          </div>
        </div>
      </main>
    </>
  );
}
