import Head from "next/head";
import { Inter } from "next/font/google";
import {
  CourseDetailBanner,
  CourseDetailContent,
  CourseVideoCard,
} from "@/components/pages";
import {NodataFound} from '@/components/common'
import { useEffect, useState } from "react";
import { EXIST_LOCAL_STORAGE } from "@/services/constants";
import { getStorage } from "@/services/helperFunctions";

const inter = Inter({ subsets: ["latin"] });
export default function CourseDetail() {
  const [courseDetails, setCourseDetails] = useState({});
  const [sendSelectedTopic, setSendSelectedTopic] = useState({});

  useEffect(() => {
    try {
      const courseDetails =
        JSON.parse(getStorage(EXIST_LOCAL_STORAGE.COURSE_DETAIL)) || {};
      

        if(courseDetails?.syllabusList.length >0){
          if (courseDetails?.syllabusList[0]?.topics[0]) {
            const selectedTopic =
              courseDetails?.syllabusList[0].topics[0];
                setSendSelectedTopic(selectedTopic);
          }
        }

    

      setCourseDetails(courseDetails);
    } catch (e) {
      console.log(e)
    }
  }, []);



  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`vh-100 ${inter.className}`}>
        {courseDetails?.syllabusList?.length >0?
        <div className="container">
          <div className="row">
            <div className="col-8">
              <CourseVideoCard
                courseDetails={courseDetails}
                sendSelectedTopic={sendSelectedTopic}
              />
            </div>
            <div className="col-4">
              <CourseDetailContent
                sendSelectedTopic={setSendSelectedTopic}
                courseDetails={courseDetails}
              />
            </div>
          </div>
        </div>: <NodataFound title="No syllabus yet"  subTitle="You can go to back by clicking below button"/>}
      </main>
    </>
  );
}
