import Head from 'next/head'
import { Inter } from 'next/font/google'
import { CourseDetailBanner,CourseDetailContent,N } from '../../components/pages'


const inter = Inter({ subsets: ['latin'] })
import { Banner, OurPromis, ContactUsForm } from '@/components/pages'
export default function CourseDetail() {


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`vh-100 ${inter.className}`}>


                <div className='row'>
                    <div className='col-12'>
                        <CourseDetailBanner />
                        <CourseDetailContent/>
                    </div>
                </div>


            </main>
        </>
    )
}
