import Head from 'next/head'
import { Inter } from 'next/font/google'
import { CourseDetailBanner,CourseDetailContent,OurCoursesCard } from '@/components/pages'


const inter = Inter({ subsets: ['latin'] })
export default function CourseDetail() {


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${inter.className}`}>


                <div className='row'>
                    <div className='col-12'>
                        <OurCoursesCard isSwiper={false} isViewAllBtn={false} />
                        {/* <CourseDetailContent/> */}
                    </div>
                </div>


            </main>
        </>
    )
}
